
All except for multiple conditions
https://forum.powerpivotpro.com/forums/topic/multiple-allexcept-in-same-calc/

Splitting columns by delimeter with DAX
https://community.powerbi.com/t5/Desktop/Splitting-columns-by-Delimiter-with-DAX-No-Query-Editor/td-p/995543

Statfin date format (for finnish data)
1. Create a new custom column and paste: "01." & Text.Range([Kuukausi], 5, 2) & "." & Text.Range([Kuukausi], 0,  4)
2. Name the custom column Date
3. Add a new step after custom column and paste: = Table.TransformColumnTypes(#"Added Custom",{{"Date", type date}})

Other way to do this is add empty step and use this code (just change #"Filtered Rows" with one correct in your case)
= Table.AddColumn(#"Filtered Rows", "pvm", each "01." & Text.Range([Kuukausi], 5, 2) & "." & Text.Range([Kuukausi], 0,  4), type date)
